### PR TITLE
Updated the TS Library

### PR DESCRIPTION
**Pull request by goetzrrGit**
We didn't update the TS type file on @cartermak  last PR https://github.com/NASA-AMMOS/seq-json-schema/pull/26

Includes the new immediate_load and immediate_activate by running `npm run prepublishOnly`

### CODE REVIEW

**Review by Mythicaeda — APPROVED** [review]
Is it possible to add a workflow automation to check for if the type-generating script hasn't been run (or to run the script)?

I think so, we don't have any workflow automation on the project atm :(

**Comment by goetzrrGit** [comment]
> Is it possible to add a workflow automation to check for if the type-generating script hasn't been run (or to run the script)?
> 

I think so, we don't have any workflow automation on the project atm :(

**Comment by duranb** [comment]
> > Is it possible to add a workflow automation to check for if the type-generating script hasn't been run (or to run the script)?
> 
> I think so, we don't have any workflow automation on the project atm :(

`prepublishOnly` should be automatically run when you run `npm publish` and the generated `types.ts` and `schema.json` files are included in the npm package.  You technically could ignore those two files from git so you don't have to keep updating it on git when the script is updated.

**Comment by goetzrrGit** [comment]
@duranb Are you saying this PR isn't really needed?

**Comment by duranb** [comment]
> @duranb Are you saying this PR isn't really needed?

I think so. Unless you find it beneficial to have the type accessible via the repo as well. I also haven't installed the package to confirm the files are included. I was just looking at the `package.json` to see what was included under `files`.

**Comment by goetzrrGit** [comment]
> > @duranb Are you saying this PR isn't really needed?
> 
> I think so. Unless you find it beneficial to have the type accessible via the repo as well. I also haven't installed the package to confirm the files are included. I was just looking at the `package.json` to see what was included under `files`.

Got it. I will merge the PR as I use it sometimes as a reference or quick lookup and don't want to sift through the actual json spec which is not very readable

**Comment by dandelany** [comment]
FYI @cartermak ran into this same point of confusion this week so we decided to remove `types.ts` from the repo via gitignore. Users who want to use the `types.ts` file can either build this repo locally or install it via NPM/PyPI

**Pull request merged**
